// Generated by CoffeeScript 1.10.0
(function() {
  var vm;

  Vue.config.debug = true;

  Vue.config.devtools = true;

  vm = new Vue({
    el: "#vuejsviewer",
    data: {},
    ready: {},
    methods: {}
  });

}).call(this);
